In [1]:
from __future__ import print_function

In [2]:
import torch 

In [3]:
x = torch.rand(8,4)

In [4]:
x

tensor([[0.4553, 0.6385, 0.5950, 0.5530],
        [0.0136, 0.6120, 0.3546, 0.9051],
        [0.0135, 0.7659, 0.1226, 0.4931],
        [0.4353, 0.4981, 0.0836, 0.5964],
        [0.9372, 0.8489, 0.0898, 0.5424],
        [0.2627, 0.6500, 0.4493, 0.9919],
        [0.3483, 0.5460, 0.7072, 0.8722],
        [0.8593, 0.8246, 0.8623, 0.8537]])

In [5]:
x[0,4]

IndexError: index 4 is out of bounds for dimension 1 with size 4

In [7]:
x[0,3]

tensor(0.5530)

In [8]:
torch.cuda.is_available()

False

In [9]:
x = torch.empty(5,3)

In [10]:
x

tensor([[9.4429e-09, 2.6582e-06, 1.3298e+22],
        [2.1270e-07, 2.5965e+20, 2.7000e-06],
        [2.0913e+20, 2.1415e+23, 3.1087e-18],
        [1.9421e+31, 2.7491e+20, 6.1949e-04],
        [7.1856e+22, 4.3605e+27, 2.3329e-18]])

In [11]:
print(x)

tensor([[9.4429e-09, 2.6582e-06, 1.3298e+22],
        [2.1270e-07, 2.5965e+20, 2.7000e-06],
        [2.0913e+20, 2.1415e+23, 3.1087e-18],
        [1.9421e+31, 2.7491e+20, 6.1949e-04],
        [7.1856e+22, 4.3605e+27, 2.3329e-18]])


In [12]:
x = torch.rand(5,3)

In [13]:
x

tensor([[0.4913, 0.0795, 0.4296],
        [0.6488, 0.0408, 0.3939],
        [0.6134, 0.0092, 0.5903],
        [0.9250, 0.2451, 0.8375],
        [0.7592, 0.1257, 0.9390]])

In [14]:
x = x.new_ones(5, 3, dtype=torch.double)  

In [15]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [16]:
x = x.new_ones(5, 3, dtype=torch.float)  

In [17]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
x = torch.randn_like(x, dtype=torch.float) 

In [19]:
x

tensor([[ 0.4260, -0.6266,  0.9285],
        [-2.6710, -0.9744,  1.0920],
        [-1.2420, -0.7346,  0.5411],
        [ 1.6219,  0.7440,  1.2810],
        [-0.1005, -0.4904,  1.5650]])

In [21]:
x.size()

torch.Size([5, 3])

In [22]:
y = torch.randn_like(x, dtype=torch.float) 

In [23]:
y

tensor([[ 0.7499, -1.5272,  0.1325],
        [ 0.1310, -2.0103,  1.5235],
        [ 0.6246,  0.1925,  0.8613],
        [-0.8844, -0.2923, -2.1215],
        [-0.8231, -0.3114,  1.0141]])

In [24]:
x+y

tensor([[ 1.1759, -2.1538,  1.0611],
        [-2.5400, -2.9847,  2.6155],
        [-0.6174, -0.5421,  1.4023],
        [ 0.7376,  0.4518, -0.8405],
        [-0.9236, -0.8017,  2.5791]])

In [25]:
torch.empty([5,3])

tensor([[-4.4910e+30,  4.5719e-41, -4.4910e+30],
        [ 4.5719e-41,  2.0103e+00,  1.5235e+00],
        [ 6.2458e-01,  1.9248e-01,  8.6127e-01],
        [ 8.8438e-01,  2.9228e-01,  2.1215e+00],
        [ 8.2309e-01,  3.1137e-01,  1.0141e+00]])

In [26]:
x

tensor([[ 0.4260, -0.6266,  0.9285],
        [-2.6710, -0.9744,  1.0920],
        [-1.2420, -0.7346,  0.5411],
        [ 1.6219,  0.7440,  1.2810],
        [-0.1005, -0.4904,  1.5650]])

In [35]:
x.view(-1,15)

tensor([[ 0.4260, -0.6266,  0.9285, -2.6710, -0.9744,  1.0920, -1.2420, -0.7346,
          0.5411,  1.6219,  0.7440,  1.2810, -0.1005, -0.4904,  1.5650]])

In [36]:
x.size()

torch.Size([5, 3])

In [40]:
x[:,:]

tensor([[ 0.4260, -0.6266,  0.9285],
        [-2.6710, -0.9744,  1.0920],
        [-1.2420, -0.7346,  0.5411],
        [ 1.6219,  0.7440,  1.2810],
        [-0.1005, -0.4904,  1.5650]])

In [43]:
x[0,0].item()

0.42599794268608093